name: Docker

permissions:
  id-token: write
  contents: read # This is required for actions/checkout@v2

on:
  push:
    # Publish semver tags as releases.  This restricts tags to only releases tagged as x.x.x
    tags: [ '*.*.*' ]

env:
  ECR_REPOSITORY: ${{ github.event.repository.name }}
  # This pulls in the referenced version version tags passed from github
  IMAGE_TAG: ${{ github.ref_name }} 
  
jobs:
  build:
  
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # Use OICD credentials
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          # Build a docker container and tag it as both the $IMAGE_TAG and latest
          # push it to ECR 
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY --all-tags
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"